crawler:
  container_name: elk_crawler
  build: ./crawler
  volumes:
    - ..:/code
    - /mnt/data/logstash:/data
  working_dir: /code
  command: python crawler.py
  restart: unless-stopped

elastic:
  container_name: elk_elastic
  build: ./elasticsearch
  ports:
    - "9200:9200"
  volumes:
    - /mnt/data/elasticsearch:/elastic_data
  restart: unless-stopped
  environment:
    ES_HEAP_SIZE: 4g

logstash:
  container_name: elk_logstash
  build: ./logstash
  volumes:
    - /mnt/data/logstash:/data
  entrypoint: ./entrypoint.sh
  command: ./bin/logstash -f ./config/logstash.conf
  restart: unless-stopped
  links:
    - elastic
  environment:
    LS_HEAP_SIZE: 2g

kibana:
  container_name: elk_kibana
  # build: ./kibana
  image: kibana:4.2.1
  restart: unless-stopped
  environment:
    ELASTICSEARCH_URL: http://elastic:9200
  ports:
    - "5601:5601"
  links:
    - elastic



